update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    if is_ci do 
      setup_ci()
    end
  end

  # Run coverage
  lane :test_xcov do 
    xcov(
      workspace: "Collecionarium.xcworkspace",
      scheme: "Collecionarium",
      output_directory: "xcov_output",
      coveralls_repo_token: "iLlWpn6p1OuKIz4O4Q6KBMXfeWPs4SqgH"
    )  
  end

  # Run coverage
  lane :test_slather do 
    slather(html: true, coveralls: true)
  end
end
