update_fastlane

default_platform(:ios)

platform :ios do
  # Install dependencies
  lane :install do
    cocoapods
  end

  lane :test do
    scan()
  end

  # Run coverage
  lane :coverage_xcov do 
    xcov(
      workspace: "Collecionarium.xcworkspace",
      scheme: "Collecionarium",
      output_directory: "xcov_output",
      coveralls_repo_token: ENV["COVERALLS_REPO_TOKEN"]
    )  
  end

  # Run coverage
  lane :coverage_slather do 
    slather(html: true, coveralls: true)
  end
end
