name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get dependencies
      run: sudo gem install fastlane
    - name: Fastlane test
      run: bundle exec fastlane test
